name: "GitHub Action for Factorio Mod Release"
description: "Upload a Factorio mod to the mod portal."
author: "Nicolas Lang"
branding:
  icon: "upload"
  color: "orange"
inputs:
  MOD_UPLOAD_API_KEY:
    description: "Api key that will be used to authenticate to the Factorio mod-portal."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
